Core 1941/super gradients integration
Unstructured-IO/unstructured-inference pull request #246
Opened 2023-10-11 02:27 UTC by pravin-unstructured

Add new detection class which allows the user to supply a super-gradients model with the following values;
1. model_arch supported by super-gradients
2. model_path to the model weights
3. yaml file with a names section containing in order the labels for the classes to the object detection model
4. callback function which takes an image and a super-gradients model and returns supervision detections

Wlll be used for AF contract and contracts in the future.

2023-10-11 16:39 UTC, MthwRobinson reviewed
Main thought from me is that we probably want to make the new dependencies extras if only a limited set of users will use the super gradients functionality.

2023-10-11 16:39 UTC, MthwRobinson commented on requirements/base.in
> +super-gradients
Will most `unstructured` users use the super gradients functionality? If not we may want to make these extras to keep the base installation as slim as possible.

2023-10-11 21:11 UTC, MthwRobinson approved these changes
LGTM! Discussed a few things offline w/ @qued

2023-10-11 23:38 UTC, qued requested changes
Adding a hold to make sure release happens before this merges.

2023-10-13 02:46 UTC, qued approved these changes

2023-10-13 03:13 UTC, merged